- platform: cast
  host: 192.168.1.112
- platform: kodi
  host: 192.168.1.126
  username: usermane
  password: pass
  
- platform: broadlink
  name: Home Media
  host: 192.168.1.151
  mac: '34:EA:34:42:E6:91'
  ircodes_ini: 'custom_components/broadlink_media_codes/home.ini'
  ping_host: 192.168.1.165
