
- platform: broadlink
  host: 192.168.1.151
  mac: '34:EA:34:42:E6:91'
  switches:
    hisense:
      friendly_name: "TV"
      command_on: 'JgBYAAABJpQSExETExITEhITEhMSExETEjcSNxI3EzYTNxI3EhMSNxI3ExIROBE4EhITExISExMQFBI3EhMSExE4ETgROBE4EgAFTAABJkoSAAxPAAEmShEADQU='
      command_off: 'JgBYAAABJpQSExETExITEhITEhMSExETEjcSNxI3EzYTNxI3EhMSNxI3ExIROBE4EhITExISExMQFBI3EhMSExE4ETgROBE4EgAFTAABJkoSAAxPAAEmShEADQU='
    kartina:
      friendly_name: "Kartina"
      command_on: 'JgBYAAABJ5QSNxEUETgROBE4EjcSExI3EjcSNxITEhMRExMSExIRExM3FBESNxITERQQFBI3FBESExA5EhITNxI3EjcSExI3EgAFJwABJ0kTAAxPAAElShEADQU='
      command_off: 'JgBYAAABJ5QSNxEUETgROBE4EjcSExI3EjcSNxITEhMRExMSExIRExM3FBESNxITERQQFBI3FBESExA5EhITNxI3EjcSExI3EgAFJwABJ0kTAAxPAAElShEADQU='
    mibox:
      friendly_name: "Mi Box"
      command_on: 'JgCcACAVEhQTMRMwEhQTMRIUEjETFBMxETITAAFjIBMTFBMwFDATFBIxEhUSMRIVEjERMhMAAWMeFhIVEjESMREWEjESFRIxExQRMhMwEwABYiEUERUSMhQvExMUMBMTEzAVEhMxEjETAAFjIBQSFBIxEzESFBIyExQSMREWEjESMRMAAWMeFhIVEjESMRIVEjESFREyExQTMBMwEwANBQAAAAAAAAAAAAAAAA=='
      command_off: 'JgCcACAVEhQTMRMwEhQTMRIUEjETFBMxETITAAFjIBMTFBMwFDATFBIxEhUSMRIVEjERMhMAAWMeFhIVEjESMREWEjESFRIxExQRMhMwEwABYiEUERUSMhQvExMUMBMTEzAVEhMxEjETAAFjIBQSFBIxEzESFBIyExQSMREWEjESMRMAAWMeFhIVEjESMRIVEjESFREyExQTMBMwEwANBQAAAAAAAAAAAAAAAA=='
    sound:
      friendly_name: "Sound Projector"
      command_on: 'JgDwAJKVDxEQEQ8SDxERMA8yEBEQEQ8yEDIPMhAyDhIPEQ8SDhIPlQ8SDxEQERARDhIQERARDxIOMw8yEDIQEA8yEDEQMg4zEBEPEg8REDIPAAdek5MQEQ8SDxIOEhAyDjMQEA4TDjMQMRAyDzIQEQ4TDhIPEg+VDxEPEg8SDxEPEQ8SEBEPERAyDzIPMw8RDzMPMRAyDzIPEg4SDxIQMg8AB1+SkxARDxIOEg8SDzIQMg4SDxIPMw4yDzIPMw8SDhIQERARD5QQEQ8SDhIQERARDhMOEg8SDzEQMg8yEBEPMhAyDzIQMQ4SDxIPEg8yDwANBQAAAAAAAAAA'
      command_off: 'JgDwAJKVDxEQEQ8SDxERMA8yEBEQEQ8yEDIPMhAyDhIPEQ8SDhIPlQ8SDxEQERARDhIQERARDxIOMw8yEDIQEA8yEDEQMg4zEBEPEg8REDIPAAdek5MQEQ8SDxIOEhAyDjMQEA4TDjMQMRAyDzIQEQ4TDhIPEg+VDxEPEg8SDxEPEQ8SEBEPERAyDzIPMw8RDzMPMRAyDzIPEg4SDxIQMg8AB1+SkxARDxIOEg8SDzIQMg4SDxIPMw4yDzIPMw8SDhIQERARD5QQEQ8SDhIQERARDhMOEg8SDzEQMg8yEBEPMhAyDzIQMQ4SDxIPEg8yDwANBQAAAAAAAAAA'
    bedroom_light:
      friendly_name: "Parents Room Light"
      command_on: "shw0ACILIgsMISIMIgsjCwwhIgsjCyILIwsjCwwhDCEiCwwhIgsMISILDCEiCwwiDCEMIQwAAVUAAAAA"
      command_off: "shk0ACILIgsjCyILDCEMISILDCEjCwwhIgsMIQwhIwsMIQwhDAABVSMLIgsMISILIgsiCwwhIgsAAAAA"
    bedroom_fan:
      friendly_name: "Parents Room Fan"
      command_on: "shQ0ACMMDCIjCw0hDSEMISILDCEMAAFVIwsiDAwiIwsjDCMLDCEjDCILIwsiCyMLDCIMIiMLDSEAAAAA"
      command_off: "shA0ACMLIgsMISMLIgsiCwwhIgwiCyILIgsjCwwhDCIiCwwhIgwMISILDCEMIQwhDCEiCwwAAVUAAAAA"  
    kitchen:
      friendly_name: "Kitchen"
      command_on: "sgw0AA0kJA0NJA0kDSQkDSQNDSQNJA0kJA0kDSQNDSQNJCQNJA0kDQ0kJA0NJCQNDSQNJAwAAW8AAAAA"
      command_off: "sgw0ACQNDSQNJCQNJA0kDSQNDSQNJCQNJA0kDQ0kDSQkDQ0kDSQNJA0kJA0kDSQNDSQkDQwAAW8AAAAA"
    living_room_2:
      friendly_name: "Living room 2"
      command_on: "shg0ACQNJA0kDQ0kJA0kDSQNJA0kDQ0kDSQkDQ0kJA0kDSQNDSQNJCQNDSQNJCQNJA0kDQwAAW8AAAAA"
      command_off: "shg0ACQNJA0kDSQNDSQkDQ0kJA0kDSQNJA0NJCQNJA0kDSQNDSQkDQ0kDSQNJCQNJA0NJAwAAW8AAAAA"  
    coridor:
      friendly_name: "Coridor"
      command_on: "sgw0AA0kJA0NJCQNJA0kDSQNDSQNJCQNJA0NJA0kJA0kDSQNDSQkDQ0kDSQNJA0kJA0NJAwAAW8AAAAA"
      command_off: "sgw0AA0kJA0NJCQNJA0NJCQNDSQNJA0kJA0NJCQNDSQNJA0kJA0kDSQNDSQNJCQNJA0kDQwAAW8AAAAA" 
    bathroom:
      friendly_name: "Bathroom"
      command_on: "sgw0AA0kDSQNJCQNJA0kDSQNDSQNJCQNDSQNJCQNJA0kDSQNJA0kDQ0kDSQkDQ0kJA0kDQwAAW8AAAAA"
      command_off: "sgw0AA0kDSQNJCQNDSQNJA0kDSQNJA0kDSQkDQ0kDSQkDSQNJA0kDSQNJA0NJA0kJA0NJAwAAW8AAAAA" 
    balcony:
      friendly_name: "Balcony"
      command_on: "shg0ACQNDSQNJCQNJA0kDQ0kJA0kDQ0kJA0NJCQNJA0NJA0kDSQNJCQNJA0NJA0kJA0NJAwAAW8AAAAA"
      command_off: "shg0AA0kDSQkDQ0kDSQkDSQNDSQkDQ0kJA0kDQ0kJA0kDSQNDSQNJCQNDSQkDQ0kDSQNJAwAAW8AAAAA"
    beauty_saloon:
      friendly_name: "Beauty Saloon"
      command_on: "sgw0ACQNJA0NJCQNDSQNJCQNJA0NJCQNDSQNJCQNJA0kDSQNJA0NJA0kDSQkDSQNJA0NJAwAAW8AAAAA"
      command_off: "sgw0AA0kJA0NJA0kJA0NJA0kDSQkDSQNDSQkDQ0kJA0NJCQNJA0NJA0kJA0kDQ0kJA0kDQwAAW8AAAAA"
    living_room_1:
      friendly_name: "Living Room 1"
      command_on: "sgw0AA0kDSQNJCQNJA0NJCQNDSQkDQ0kDSQkDQ0kDSQNJA0kDSQkDSQNDSQkDSQNDSQkDQwAAW8AAAAA"
      command_off: "sgw0AA0kDSQNJA0kJA0kDSQNDSQkDQ0kJA0kDQ0kDSQNJA0kJA0NJCQNDSQNJCQNJA0NJAwAAW8AAAAA"     
    enterence:
      friendly_name: "Enterence"
      command_on: "sgw0AA0kDSQNJCQNDSQNJCQNJA0kDQ0kJA0kDSQNJA0kDQ0kJA0NJA0kJA0NJA0kJA0kDQwAAW8AAAAA"
      command_off: "sgw0ACQNDSQkDSQNJA0kDQ0kJA0NJCQNDSQNJA0kJA0kDQ0kDSQkDQ0kJA0NJA0kDSQkDQwAAW8AAAAA"
    victoria_room:
      friendly_name: "Victorias Room"
      command_on: "sgw0AA0kJA0NJCQNJA0NJA0kJA0kDQ0kDSQNJCQNJA0NJCQNDSQkDSQNJA0NJCQNDSQkDQwAAW8AAAAA"
      command_off: "sgw0ACQNDSQkDSQNJA0NJA0kJA0NJCQNJA0kDQ0kJA0NJA0kDSQNJA0kJA0kDQ0kDSQkDQwAAW8AAAAA"  
    work_room:
      friendly_name: "Work Room"
      command_on: "sgw0ACQNJA0kDSQNDSQNJCQNDSQkDSQNDSQNJCQNJA0NJCQNJA0NJCQNDSQkDSQNJA0kDQwAAW8AAAAA"
      command_off: "sgw0ACQNDSQkDQ0kJA0NJA0kDSQNJCQNJA0NJA0kJA0NJA0kJA0NJCQNDSQkDSQNJA0kDQwAAW8AAAAA"
    service_room:
      friendly_name: "Service Room"
      command_on: "sgw0ACQNJA0kDQ0kDSQkDQ0kDSQkDSQNDSQNJCQNJA0NJCQNDSQkDQ0kJA0NJA0kDSQNJAwAAW8AAAAA"
      command_off: "sgw0ACQNDSQkDQ0kDSQNJA0kDSQkDQ0kDSQNJA0kDSQkDQ0kDSQkDSQNJA0kDSQNJA0kDQwAAW8AAAAA"    


- platform: command_line
  switches:
    boiler:
      friendly_name: Boiler
      command_on: /home/homeassistant/.homeassistant/scripts/broadlink_send "sh80ACUMJQwQIRAiDyElDA8iDyIPIiUMJQwlDCUMDyIPIg8iDyElDA8hJQwPIQ8iJQwPIhAAAWYAAAAA"
      command_off: /home/homeassistant/.homeassistant/scripts/broadlink_send "sis0AA8iJQwQIRAhDyIlDBEAAWYlDCUMDyEQIhAhJQwQIg8hDyIlDCUMJQwlDA8hDyIQIg8hJgwAAAAA"
    air_cond_api:
      friendly_name: Air Conditioner
      command_on: /home/homeassistant/.homeassistant/scripts/airCondOnApi
      command_off: /home/homeassistant/.homeassistant/scripts/airCondOffApi
      command_state: /home/homeassistant/.homeassistant/scripts/airCondStateApi
    hisense:  
      friendly_name: Hisense
      command_on: /home/homeassistant/.homeassistant/scripts/broadlink_send "JgBYAAABJpQSExETExITEhITEhMSExETEjcSNxI3EzYTNxI3EhMSNxI3ExIROBE4EhITExISExMQFBI3EhMSExE4ETgROBE4EgAFTAABJkoSAAxPAAEmShEADQU="
      command_off: /home/homeassistant/.homeassistant/scripts/broadlink_send "JgBYAAABJpQSExETExITEhITEhMSExETEjcSNxI3EzYTNxI3EhMSNxI3ExIROBE4EhITExISExMQFBI3EhMSExE4ETgROBE4EgAFTAABJkoSAAxPAAEmShEADQU="
      command_state: fping 192.168.1.165      
      
- platform: broadlink
  host: 192.168.1.118
  mac: '34:EA:34:42:BA:F6'      
  switches:
    bedroom_ac_virtual:
      friendly_name: "Bedroom Morning Heat"
      command_on: 'JgDKAJOREzMTERM0FDITERMREzMUERISEzMUEBMREzQSNBMREzMTEhMREjQTNBI0EzMTNBMzFTISNBMRExETERMRExISEhMzEzMUERISEjQUMhMSEhISEhMRETUTNBMRFBATMxM0E7mTkRM0EhITMxQzEhISEhI0ExESEhM0ExEUEBI0EzQSEhMzExETERM0EjQUMxMzEzMTNBMzEzQSEhMRExETERMRExEUMxI0ExESEhMzEzQSEhMREhITERI1EzMTERMREzQSNBMADQUAAAAAAAAAAAAAAAAAAA=='
      command_off: 'JgDKAJORFDMTERM0EzMTERMSEjQTERMREzQTERMREzQTMxISEzQTERMzEzQTMxMzFBETNBMzEzQTERMRExETERM0ExETERM0EjQTNBMRExETERMRExETERMSEhITMxM0EzMTNBMzE7qTkRQzEhITNBMzExETEhI0ExETERI1EhITERI1EzMTERI1ExESNBM0EzMTNBMREzMUMxM0ExETERMREhISNRISEhISNBI1EzMTERMSEhISEhMRExESEhMREjUTMxM0EzMTNBIADQUAAAAAAAAAAAAAAAAAAA=='
  
